services:
  app:
    container_name: go-api
    build:
      context: .
      dockerfile: Dockerfile
    image: go-api
    ports:
      - 8080:8080
    networks:
      - go-network


networks:
  go-network:
    driver: bridge
